"""Metric definitions, grouping, and reporting."""

from __future__ import annotations

from .core import (
    METRIC_DEFINITIONS,
    PRIMARY_METRICS,
    SUPPORTING_METRICS,
    DefenseComparison,
    Metric,
    applicable_rows,
    attack_success_rate,
    blocked_call_rate,
    compare_defense,
    compute_metrics,
    error_rate,
    group_by,
    injection_delivery_rate,
    is_applicable,
    metrics_by,
    safe_completion_rate,
    sensitive_information_exposure_rate,
    system_prompt_leak_rate,
    task_completion_rate,
    unauthorized_tool_call_rate,
)
from .report import (
    HEADLINE_METRICS,
    SHORT_NAMES,
    attach_condition,
    build_defense_comparisons,
    build_provisioning_comparisons,
    condition_key,
    csv_rows_for_categories,
    csv_rows_for_conditions,
    render_markdown,
    render_table,
    summarise,
)
from .stats import wilson_interval, two_proportion_z_test

__all__ = [
    "DefenseComparison",
    "HEADLINE_METRICS",
    "METRIC_DEFINITIONS",
    "Metric",
    "PRIMARY_METRICS",
    "SHORT_NAMES",
    "SUPPORTING_METRICS",
    "applicable_rows",
    "attach_condition",
    "attack_success_rate",
    "blocked_call_rate",
    "build_defense_comparisons",
    "build_provisioning_comparisons",
    "compare_defense",
    "compute_metrics",
    "condition_key",
    "csv_rows_for_categories",
    "csv_rows_for_conditions",
    "error_rate",
    "group_by",
    "injection_delivery_rate",
    "is_applicable",
    "metrics_by",
    "render_markdown",
    "render_table",
    "safe_completion_rate",
    "sensitive_information_exposure_rate",
    "summarise",
    "system_prompt_leak_rate",
    "task_completion_rate",
    "two_proportion_z_test",
    "unauthorized_tool_call_rate",
    "wilson_interval",
]
